export const APP_TEXT = {
	signIn: 'Sign in',
	forgotPassword: 'Forgot your password?',
	dontHaveAccount: 'Don’t have an account yet?',
	pageNotFound: 'Page not found',
	goBackHome: 'Go back home',
	dontHaveAccess: 'Sorry, but you do not have access to this page',
	accumulated: 'Accumulated',
	goal: 'Goal',
	items: 'Items',
	create: 'Create',
	fund: 'Fund',
	transfer: 'Transfer',
	more: 'More',
	continue: 'Continue',
	search: 'Search',
	targetAmount: 'Target amount',
} as const;
