name: pull-request-master
on:
  pull_request:
      branches: [ "master" ]
  workflow_dispatch:
      
jobs:
          
  build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Используем код из PR1
      - uses: actions/setup-node@v4

      - run: npm update
      - run: npm run build

      - name: Upload Build Folder as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

          
  deploy:
    if: ${{ github.event_name == 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
    
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: mkdir
        run: mkdir dist

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Verify Renamed Folder
        run: |
          ls -la /home/runner/work/finance-web/finance-web/dist/

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy with rsync
        run: scp -r /home/runner/work/finance-web/finance-web/dist/ ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/admin/app/web/

  test:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Используем код из PR
      - uses: actions/setup-node@v4

      - run: npm update
      - run: npm run build
