name: test_pull_request
on:
  workflow_call:
    inputs:
      job-to-run:
        description: 'Job to run (tests)'
        type: string
        required: true

jobs:
  tests:
    if: ${{ github.event.inputs.job-to-run == 'tests' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # Используем код из PR
      - uses: actions/setup-node@v4

      - run: npm update
      - run: npm run build
